// views/format-site/Footer.tsx

export interface FooterProps {
  idea: string;
}

export default ({ idea }: FooterProps) => (
  <footer>
    <p>
      Generated by pure evil just from the string: <code> {idea} </code>
    </p>
  </footer>
);
